bin: update to conform somewhat to standards

diff --git a/local/bin/copy b/local/bin/copy
--- a/local/bin/copy
+++ b/local/bin/copy
@@ -1,15 +1,23 @@
 #!/usr/bin/env bash
-if [ -z "$DISPLAY" ]; then
-	echo "Error: Display must be available"
-	exit 1
-fi
+has_display() {
+	[[ -n "$DISPLAY" ]]
+}
 
-if [ $# -eq 0 ]; then
-	xclip
-else
-	if [ -f "$*" ]; then
-		xclip "$*"
-	else
-		echo -n "$*" | xclip
+main() {
+	if ! has_display; then
+		echo "Error: Display must be available"
+		exit 1
 	fi
-fi
+
+	if [[ $# -eq 0 ]]; then
+		xclip
+	else
+		if [[ -f "$*" ]]; then
+			xclip "$*"
+		else
+			echo -n "$*" | xclip
+		fi
+	fi
+}
+
+main "$@"
diff --git a/local/bin/cpv b/local/bin/cpv
--- a/local/bin/cpv
+++ b/local/bin/cpv
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
-if [ ! $# -eq 2 ]; then
-	echo "Error: You must provide a source and a target"
-	exit 1
-fi
+main() {
+	if [[ ! $# -eq 2 ]]; then
+		echo "Error: You must provide a source and a target"
+		exit 1
+	fi
 
-rsync -r -poghb --backup-dir=/tmp/rsync -e /dev/null --progress -- "$1" "$2"
+	rsync -r -poghb --backup-dir=/tmp/rsync -e /dev/null --progress -- "$1" "$2"
+}
+
+main "$@"
