bin: cleanup vrun
- Extract different parts to methods.
- Make some performance improvements.
- Don't always pre-run with true-check which adds another 40ms.

diff --git a/local/bin/vrun b/local/bin/vrun
--- a/local/bin/vrun
+++ b/local/bin/vrun
@@ -1,42 +1,48 @@
 #!/usr/bin/env bash
-if [ ! -f "${PWD}/Vagrantfile" ]; then
-	echo 'Error: No Vagrantfile in current directory'
-	exit 1
-fi
+SSH_CONFIG_CACHE="/tmp/vagrant-ssh-config-${PWD//\//%}"
 
-ssh_config_cache="/tmp/vagrant-ssh-config-$(echo $PWD | tr / %)"
+cache_ssh_config() {
+	vagrant ssh-config > "$SSH_CONFIG_CACHE"
+}
 
-if [ -f "$ssh_config_cache" ]; then
-	ssh -q -F $ssh_config_cache default true
-else
-	vagrant ssh-config > "$ssh_config_cache"
-fi
+run() {
+	if [[ ! -f "$SSH_CONFIG_CACHE" ]]; then
+		cache_ssh_config
+	fi
 
-exit_code=$?
-cmd=''
+	cmd=''
+	# Escape white-space to retain proper arguments
+	for i in "$@"; do
+		cmd+=${i// /'\ '}' '
+	done
 
-# Escape white-space to retain proper arguments
-for i in "$@"; do
-	cmd+=${i// /'\ '}' '
-done
+	cmd="cd /vagrant; bash -l -c '${cmd}'"
+	ssh -t -t -q -F $SSH_CONFIG_CACHE default -- $cmd
+}
 
-if [ $exit_code -eq 0 ]; then
-	cmd='cd /vagrant; bash -l -c "'${cmd}'"'
-	ssh -t -t -q -F $ssh_config_cache default -- $cmd
-else
-	echo
-	echo 'Error: Could not connect to vagrant'
-	rm "$ssh_config_cache"
+initialize() {
+	if [[ ! -f "${PWD}/Vagrantfile" ]]; then
+		echo 'Error: No Vagrantfile in current directory'
+		exit 1
+	fi
 
-	read -n 1 -p "Do you want to start vagrant and retry? [y/N] " choice
-	case $choice in
-		[Yy]* )
-			echo
-			vagrant up && vrun $cmd
-			;;
-		* )
-			echo
-			exit $exit_code
-			;;
-	esac
-fi
+	run "$@"
+	exit_code=$?
+
+	if [[ $exit_code -eq 255 ]]; then
+		echo
+		echo 'Error: Could not connect to vagrant'
+		rm "$SSH_CONFIG_CACHE"
+
+		read -n 1 -p "Do you want to start vagrant and retry? [y/N] " choice
+		echo
+		case $choice in
+			[Yy]*) vagrant up && run "$@" ;;
+			*)     exit $exit_code        ;;
+		esac
+	else
+		exit $exit_code
+	fi
+}
+
+initialize "$@"
